### ISSUE TITLE
Have camera datas from Arnold in EXR

### ISSUE THREAD

**Issue by ClementHector** [quadproduction/OpenPype#325]
In GitLab by @kekefreedog on Mar 1, 2023, 09:38

> From Olivier Osotimehin

## Need

In Maya submitter, we have to bring camera datas into the EXR

**Comment by ccaillot** [comment]
Need to be pushed on our studio branch (The changes affects fixstudio only)

**Comment by ClementHector** [comment]
I would like to explore if it is possible to put it in a repository that will contain all our quad specific pyblish plugins. it will be easier to maintain.

**Comment by ccaillot** [comment]
@ClementHector this repository has been created for this kind of case (https://github.com/quadproduction/quad-plugins), the changes for this ticket will be implemented into it soon.
Once it will be done, we'll need a CI/CD solution as the quad-modules repository to be set

**Comment by ccaillot** [comment]
The repository has been setted and it works for the `Publish Arnold Camera Metadata`, I had some trouble to find the best way to set it up, I followed the old logic (https://openpype.io/docs/pype2/admin_presets_plugins/) but it still working, I'm not sure about this solution for the futur. I've added `load.json`, `load.json`, `publish.json` in the repo in order to initialize the logic.

The github runner are currently not running because it does not exists at the moment (Its/Systems are aware of and currently working on it). In order to be tested asap, I've deployed a first version 0.0.1 on the network.

**Comment by ccaillot** [comment]
I've deployed a new logic which use `IPluginPaths()` Class provided by Openpype, this class allow use to manage different plugin path for different hosts as the path is referenced in the `get_plugin_paths() `function (cf. https://github.com/quadproduction/OpenPype/tree/develop/openpype/modules#ipluginpaths).

In order to use `IPluginPaths()`, I had to create an `OpenPypeModule()` and update the QUAD_PLUGIN_PATH environnment variable.

**Comment by OlivierOsotimehin** [comment]
hello, how is going this feature ? is it fully deplyoed ? can we test it in nuke ?

**Comment by ccaillot** [comment]
Hello, the feature has been deployed since a while now, it should works in Nuke. Please, be aware, the Arnold Metadata appears only on sequence which has been rendered through Maya

**Comment by OlivierOsotimehin** [comment]
oh thanks, the status has never been put on done, so we didn't know ...

**Comment by OlivierOsotimehin** [comment]
will have to wait till we have the nuke script to read the data to test

**Comment by OlivierOsotimehin** [comment]
i managed to test with the nuke py script it is working thanks
