### ISSUE TITLE
Bug: published render version is a static image instead of being a movie

### ISSUE THREAD

**Issue by OlivierOsotimehin** [quadproduction/OpenPype#423]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

the published render version is a static image instead of being a movie 

can test on asset cube task shading in TEST_OP2PUB_23_7
https://fixstudio.ftrackapp.com/#slideEntityId=4c3f8460-dd09-11ed-baa1-06178ac4037d&slideEntityType=task&view=tasks&itemId=projects&entityId=acb580f4-bf93-4a84-b10c-e14e8e666947&entityType=show

the  color space is wrong also 

### Expected Behavior:

![image](https://github.com/quadproduction/OpenPype/assets/59604835/afff7c4c-51df-44dd-b553-5620b758a493)

this but as a movie (this is a turnaround)

### Version

3.15.9-nightly.1

### What platform you are running OpenPype on?

Linux / Centos

### Steps To Reproduce:

can test on asset cube task shading in TEST_OP2PUB_23_7

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by ccaillot** [comment]
Hello Olivier, I had investigated your issue, in order to create movie in ftrack, you should use in Maya, 'Create>Review', it will be create a Review Node where you put your camera into (Drag And Drop the camera node), at publishing time, you should see something like that.

![Image](https://github.com/quadproduction/OpenPype/assets/134272390/d2876e56-39d8-4ffa-841a-15fe7b799387)

Once it will be published, it will create 2 jobs in Deadline, if you met some errors with the Maya Jobs, in Deadline you can remove in the environment Variable: OPENPYPE_VERSION in the 'environment' tabs of the 'Job Properties' (Job > Right Click > Modify Job Properties) and set to 'False' the 'Enable Strict Error Checking' field in Maya Batch Settings.

You can also met some errors with the Publish Job, you can remov the environement Variable: OPENPYPE_VERSION, IS_TEST in the 'environment' tabs and it will works.

**Comment by OlivierOsotimehin** [comment]
Thanks for the investigations
But i dont understand, is it instructions to make a playblast review or to have a review version of the exr ? 
I m not in front of my computer right now will test tomorrow

**Comment by OlivierOsotimehin** [comment]
Oh, i already know how to make opengl review with openpype

**Comment by ClementHector** [comment]
@OlivierOsotimehin Is that what you’re waiting for? https://fixstudio.ftrackapp.com/player/tempdata/9f2bd456-7198-4962-9280-90a70aa36888

**Comment by OlivierOsotimehin** [comment]
We are nearly there ! 
What's missing : 
the static frame publish is straight linear :
![image](https://github.com/quadproduction/OpenPype/assets/59604835/12ef0d23-a61c-45f2-ad81-44fb0a516537)

the movie playing is not the right color space (probably simple srgb/rec709 instead of odt srgb (the exr is acescg)) :
![image](https://github.com/quadproduction/OpenPype/assets/59604835/2368bcb8-6c8b-4ffd-8bbe-4f2864703c1c)


the right colorspace of the image is visible in the first post of the thread (Expected behavior)

**Comment by OlivierOsotimehin** [comment]
i put it again here : 
![image](https://github.com/quadproduction/OpenPype/assets/59604835/b9612163-efd0-4a30-a189-dc17790cae13)

**Comment by louparis** [comment]
The colorspace bug will be taken care of in a new ticket : #466
